### ISSUE TITLE
results layout on mobile 

### ISSUE THREAD

**Issue by photomedia** [spokenwebsites/ADP_Front#7]
The layout for search results on a mobile needs some CSS work, here is what it looks like:
![IMG_5861](https://user-images.githubusercontent.com/4087478/199516342-5ddcb476-a3a8-4161-a32d-37d7890666e0.PNG)
It needs to display only 1 card per row on a mobile, I think.

**Comment by Brijeshlakkad** [comment]
@photomedia 
I agree!
I am setting this as a priority. Let me know if you have any other suggestions. :)
